/*
 * template_definitions.hpp
 *
 *  Created on: Jan 23, 2017
 *      Author: ilion
 */

#ifndef _GRIBPP_OCTET_MAPPING_TEMPLATE_DEFINITIONS_HPP_
#define _GRIBPP_OCTET_MAPPING_TEMPLATE_DEFINITIONS_HPP_

#include <cstdint>

namespace gribpp {
	namespace octet_mapping {

		enum class template_definitions : std::uint16_t {
			//-- 0x --
			LATITUDE_LONGITUDE = 0,
			ROTATED_LATITUDE_LONGITUDE = 1,
			STRETCHED_LATITUDE_LONGITUDE = 2,
			STRETCHED_AND_ROTATED_LATITUDE_LONGITUDE = 3,
			//-- 1x --
			MERCATOR = 10,
			//-- 2x --
			POLAR_STEREOGRAPHIC_PROJECTION = 20,
			//-- 3x --
			LAMBERT_CONFORMAL = 30,
			ALBERS_EQUAL_AREA = 31,
			//-- 4x --
			GAUSSIAN_LATITUDE_LONGITUDE = 40,
			ROTATED_GAUSSIAN_LATITUDE_LONGITUDE = 41,
			STRETCHED_GAUSSIAN_LATITUDE_LONGITUDE = 42,
			STRETCHED_AND_ROTATED_GAUSSIAN_LATITUDE_LONGITUDE = 43,
			//-- 5x --
			SHPERICAL_HARMONIC_COEFFICIENTS = 50,
			ROTATED_SHPERICAL_HARMONIC_COEFFICIENTS = 51,
			STRETCHED_SHPERICAL_HARMONIC_COEFFICIENTS = 52,
			STRETCHED_AND_ROTATED_SHPERICAL_HARMONIC_COEFFICIENTS = 53,
			//-- 9x --
			SPACE_VIEW_PERSPECTIVE = 90,
			//-- 10x --
			TRIANGULAR_GRID_BASED_ON_ICOSAHEDRON = 100,
			//-- 11x --
			EQUATORIAL_AZIMUTHAL_EQUIDISTANT_PROJECTION = 110,
			//-- 12x --
			AZIMUTH_RANGE_PROJECTION = 120,
			//-- 100x --
			CROSS_SECTION_GRID = 1000,
			//-- 110x --
			HOVMJOLLER_DIAGRAM_GRID = 1100,
			//-- 120x --
			TIME_SECTION_GRID = 1200

		};

	};	//-- namespace octet_mapping --
};	//-- namespace gribpp --



#endif /* _GRIBPP_OCTET_MAPPING_TEMPLATE_DEFINITIONS_HPP_ */
